

//* Fetch
export const FETCH_POSTDATA = 'FETCH_POSTDATA'
export const FETCH_POSTDATA_FULFILLED = 'FETCH_POSTDATA_FULFILLED'
export const FETCH_POSTDATA_REJECTED = 'FETCH_POSTDATA_REJECTED'

//* Delete
export const DELETE_POSTDATA = 'DELETE_POSTDATA'
export const DELETE_POSTDATA_FULFILLED = 'DELETE_POSTDATA_FULFILLED'
export const DELETE_POSTDATA_REJECTED = 'DELETE_POSTDATA_REJECTED'

//* Add
export const ADD_POSTDATA = 'ADD_POSTDATA'
export const ADD_POSTDATA_FULFILLED = 'ADD_POSTDATA_FULFILLED'
export const ADD_POSTDATA_REJECTED = 'ADD_POSTDATA_REJECTED'

//* Update
export const UPDATE_POSTDATA = 'UPDATE_POSTDATA'
export const UPDATE_POSTDATA_FULFILLED = 'UPDATE_POSTDATA_FULFILLED'
export const UPDATE_POSTDATA_REJECTED = 'UPDATE_POSTDATA_REJECTED'
